### ISSUE TITLE
Timestamp using localtime not UTC time

### ISSUE THREAD

**Issue by gm1ymi** [gjr80/weewx-aprx#2]
APRS packets are in UTC time, not local.
Line 425 can be changed to use gmtime as opposed localtime to resolve.

Once this is changed the packets are no longer tagged as "[Delayed or out-of-order packet (timestamp)]"

**Comment by gjr80** [comment]
Guess that is indicative of how many times this extension has been used! Easy enough to fix. 

One question though. I have been trying to wade through the APRS protocol (which I found heavy going) and I see three date-time formats mentioned; local time `ddHHMM/` eg `111234/`, Zulu time `ddHHMMz` eg `110234z` and a dateless format `HHMMSSh` eg `123456h`. I also see words to the effect that Zulu time is normally used. Whilst Zulu appears to be the norm are the other two formats ever used in this context? If there is a chance they are I can easily add a config option that defaults to Zulu format but gives the user the ability to select either of the other two formats if they wish.

**Comment by gm1ymi** [comment]
Yes, it is heavy going! lol
I've only seen Zulu time used (which would make sense as it's one time format, no timezones) when there is a timestamp. 
If you look at aprs.fi you can see the raw packets come in via the Igates (RF to Internet Gateway)
https://aprs.fi/?c=raw&limit=50&call=K1YMI&view=normal&last=5563294817
First line is using the CWOP option in Weewx, second line is your extension.
![image](https://user-images.githubusercontent.com/49123416/121671286-5a058a00-ca7c-11eb-9004-164f903d690a.png)
I did find one of my local Weather stations that has no timestamp. https://aprs.fi/?c=raw&call=KC4QLP
I know that does not really help, kind of confuses matters, but I'm thinking either no timestamp or Zulu. At least with a timestamp you know your packets are making it out in the correct order and they are not getting lost. Without the timestamp you would have a harder time working out when they were transmitted.

**Comment by gjr80** [comment]
Thanks, I think we will just keep it it simple and fix the local/Zulu display issue. If anything else is required down the track its an easy change.

Fixed at commit a9d7c4dea38db2647a66643252bc34c7a16a0b94/release [v0.2.1](https://github.com/gjr80/weewx-aprx/releases/tag/v0.2.1).
